# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=20, verbose_name='sn')),
                ('Hostname', models.CharField(max_length=10, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('IP', models.CharField(max_length=20, verbose_name='\u5185\u7f51ip')),
                ('ilo_IP', models.CharField(max_length=20, verbose_name='\u5e26\u5916IP')),
                ('MAC', models.CharField(max_length=10, verbose_name='\u670d\u52a1\u5668MAC')),
                ('ilo_mac', models.CharField(max_length=10, verbose_name='\u5e26\u5916mac')),
            ],
            options={
                'ordering': ['IP'],
                'verbose_name': 'sn',
                'verbose_name_plural': 'sn',
            },
        ),
        migrations.CreateModel(
            name='Zyid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResourcesId', models.CharField(max_length=20, verbose_name='\u8d44\u6e90ID')),
                ('ProxyIp', models.CharField(max_length=20, verbose_name='\u4ee3\u7406IP\u53ca\u7535\u8bdd\u8d44\u6e90')),
                ('ResourcesType', models.CharField(max_length=20, verbose_name='\u8d44\u6e90\u7c7b\u578b')),
                ('Status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5e9f\u5f03'), (2, '\u5f85\u5b9a')], default=0, verbose_name='\u72b6\u6001')),
                ('AccountProperty', models.CharField(max_length=20, verbose_name='\u8d26\u53f7\u5c5e\u6027')),
                ('Others', models.TextField(blank=True, max_length=60, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['-ProxyIp'],
                'verbose_name': '\u8d44\u6e90ID',
                'verbose_name_plural': '\u8d44\u6e90ID',
            },
        ),
    ]
